name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build shared KMM module
        run: ./gradlew :composeApp:build

      - name: Build Android app
        run: ./gradlew :composeApp:assembleDebug
